# Generated by Django 5.1.5 on 2025-02-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_vehicle_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='dropoff_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_metadata',
            field=models.JSONField(default=dict),
        ),
    ]
