# Generated by Django 5.1.5 on 2025-03-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.bookedride'),
        ),
    ]
